---
name: Hass.io Access Point
version: 0.5.2.1
slug: hassio-access-point
description: Create a WiFi access point to directly connect devices to Home Assistant
arch: [armhf, armv7, aarch64, amd64, i386]
url: https://github.com/mattlongman/hassio-access-point
startup: system
boot: auto
host_network: true
apparmor: true
host_dbus: true
privileged:
  - NET_ADMIN
init: false
options:
  ssid:
  wpa_passphrase:
  wifi_interface: wlan0
  eth_interface: eth0
  hide_ssid: false
  allow_mac_addresses: []
  deny_mac_addresses: []
  debug: 0
  hostapd_config_override: []
schema:
  ssid: match(^.{2,32}$)
  wpa_passphrase: password
  wifi_interface: str
  eth_interface: str
  hide_ssid: bool
  allow_mac_addresses:
    - match(^([0-9a-fA-F]{2}:){4}[0-9a-fA-F]{2})?
  deny_mac_addresses:
    - match(^([0-9a-fA-F]{2}:){4}[0-9a-fA-F]{2})?
  debug: int(0,2)
  hostapd_config_override:
    - str?